const COLORS = {
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  reset: "\x1b[0m",
  blue: "\x1b[38;5;75m",
  cyan: "\x1b[38;5;81m",
  green: "\x1b[38;5;114m",
  yellow: "\x1b[38;5;221m",
  orange: "\x1b[38;5;215m",
  red: "\x1b[38;5;203m",
  magenta: "\x1b[38;5;176m",
  purple: "\x1b[38;5;141m",
  gray: "\x1b[38;5;245m",
  white: "\x1b[38;5;255m"
};

const NERD_ICONS = {
  folder: "\u{f07b} ",
  js: "\u{e781} ",
  ts: "\u{e8ca} ",
  react: "\u{e7ba} ",
  vue: "\u{e8dc} ",
  svelte: "\u{e8b7} ",
  astro: "\u{e735} ",
  style: "\u{f13c} ",
  html: "\u{f13b} ",
  config: "\u{f013} ",
  doc: "\u{f0f6} ",
  image: "\u{f1c5} ",
  video: "\u{f1c8} ",
  audio: "\u{f1c7} ",
  script: "\u{f120} ",
  archive: "\u{f1c6} ",
  test: "\u{f14a} ",
  docker: "\u{e7b0} ",
  lock: "\u{f023} ",
  hidden: "\u{f070} ",
  misc: "\u{f15b} ",
  link: "\u{f0c1} ",
  database: "\u{f1c0} ",
  graphql: "\u{e7f4} ",
  python: "\u{e73c} ",
  go: "\u{e627} ",
  rust: "\u{e7a8} ",
  php: "\u{e73d} ",
  ruby: "\u{e605} ",
  env: "\u{f013} ",
  template: "\u{f1c9} ",
  serverless: "\u{f0c2} ",
  c: "\u{e61e} ",
  csharp: "\u{e648} ",
  lua: "\u{e826} ",
  java: "\u{e738} ",
  font: "\u{e659} ",
  less: "\u{e758} ",
  json: "\u{eb0f} "
};

const EMOJI_ICONS = {
  folder: "📁 ",
  js: "🟨 ",
  ts: "📘 ",
  react: "⚛️  ",
  vue: "💚 ",
  svelte: "🧡 ",
  astro: "🚀 ",
  style: "🎨 ",
  html: "🌐 ",
  config: "⚙️  ",
  doc: "📄 ",
  image: "🖼️  ",
  video: "🎬 ",
  audio: "🎵 ",
  script: "📜 ",
  archive: "📦 ",
  test: "🧪 ",
  docker: "🐳 ",
  lock: "🔒 ",
  hidden: "👻 ",
  misc: "📌 ",
  link: "🔗 ",
  database: "🗄️  ",
  graphql: "◈ ",
  python: "🐍 ",
  go: "🔷 ",
  rust: "🦀 ",
  php: "🐘 ",
  ruby: "💎 ",
  env: "🔧 ",
  template: "📋 ",
  serverless: "☁️  ",
  c: "⚙️ ",
  csharp: "🎯 ",
  lua: "🌙 ",
  java: "☕ ",
  font: "🔤 ",
  less: "🎨 ",
  json: "📋 "
};

const ASCII_ICONS = {
  folder: "[D] ",
  js: "[J] ",
  ts: "[T] ",
  react: "[R] ",
  vue: "[V] ",
  svelte: "[S] ",
  astro: "[A] ",
  style: "[S] ",
  html: "[H] ",
  config: "[C] ",
  doc: "[F] ",
  image: "[I] ",
  video: "[V] ",
  audio: "[A] ",
  script: "[X] ",
  archive: "[Z] ",
  test: "[*] ",
  docker: "[K] ",
  lock: "[L] ",
  hidden: "[.] ",
  misc: "[-] ",
  link: "[@] ",
  database: "[#] ",
  graphql: "[Q] ",
  python: "[P] ",
  go: "[G] ",
  rust: "[R] ",
  php: "[H] ",
  ruby: "[Y] ",
  env: "[E] ",
  template: "[T] ",
  serverless: "[^] ",
  c: "[c] ",
  csharp: "[cs] ",
  lua: "[u] ",
  java: "[j] ",
  font: "[F] ",
  less: "[L] ",
  json: "[J] "
};

const DEFAULT_IGNORES = new Set([
  ".git",
  "node_modules",
  "dist",
  "build",
  "coverage",
  ".next",
  ".nuxt",
  ".svelte-kit",
  "out",
  "target",
  "vendor",
  ".turbo",
  ".cache",
  "__pycache__",
  ".pytest_cache",
  ".venv",
  "venv",
  ".terraform",
  ".serverless"
]);

function getIcons(iconSet = "nerd") {
  if (iconSet === "emoji") return EMOJI_ICONS;
  if (iconSet === "ascii") return ASCII_ICONS;
  return NERD_ICONS;
}

module.exports = {
  COLORS,
  DEFAULT_IGNORES,
  getIcons
};